// /lib/corp/config.js

export const CORP_STATE_FILE = "/data/corp-state.txt";

export const CORP_CONFIG = {
    name: "Limitless",
    selfFund: false,
    agriculture: "Agriculture",
    tobacco: "Tobacco",
    mainCity: "Sector-12",
    cities: ["Sector-12", "Aevum", "Chongqing", "New Tokyo", "Ishima", "Volhaven"],
    expansionCities: ["Aevum", "Chongqing", "New Tokyo", "Ishima", "Volhaven"],
    materialProducts: ["Food", "Plants"],
    startupJobs: [
        ["Operations", 1],
        ["Engineer", 1],
        ["Business", 1],
    ],
    growthJobs: [
        ["Operations", 3],
        ["Engineer", 2],
        ["Business", 2],
        ["Management", 1],
        ["Research & Development", 1],
    ],
    corpJobs: [
        "Operations",
        "Engineer",
        "Business",
        "Management",
        "Research & Development",
        "Intern",
    ],
    pressureSellThreshold: 0.85,
    criticalPressureSellThreshold: 0.95,
    cashRecoveryFloor: 500_000_000,
    cashStabilizeFloor: 2_000_000_000,
    officeCareReserve: 250_000_000,
    officeCareEnergyFloor: 80,
    officeCareMoraleFloor: 80,
    officeCarePartySpendPerEmployee: 1_000_000,
    agricultureStartupMaterials: [
        ["Hardware", 0.2, 1],
        ["AI Cores", 0.2, 1],
        ["Real Estate", 25, 1],
    ],
    agricultureInputs: [
        ["Water", 5],
        ["Chemicals", 2],
    ],
    agricultureStabilizeInputs: [
        ["Water", 1],
        ["Chemicals", 0.4],
    ],
    agricultureExpansionProfitFloor: 0,
    agricultureExpansionFundsFloor: 25_000_000_000,
    unlockReserve: 5_000_000_000,
    unlockMaxSpendFraction: 0.2,
    emergencyFirstOffer: 4_000_000_000,
    earlyUnlocks: [
        "Smart Supply",
        "Warehouse API",
        "Office API",
        "Export",
        "Market Research - Demand",
        "Market Data - Competition",
    ],
    priorityUnlocks: [
        "Export",
        "Market Research - Demand",
        "Market Data - Competition",
    ],
    postRound1Unlocks: [
        "Shady Accounting",
        "Government Partnership",
    ],
    productUnlocks: [
        "Market-TA.I",
        "Market-TA.II",
    ],
    agricultureRound1Materials: [
        ["Robots", 9.6, 96],
        ["Hardware", 265.7, 2800],
        ["AI Cores", 244.5, 2520],
        ["Real Estate", 11940, 146400],
    ],
    agricultureRound2Materials: [
        ["Robots", 63, 726],
        ["Hardware", 650, 9300],
        ["AI Cores", 375, 6270],
        ["Real Estate", 8400, 230400],
    ],
    firstOffer: 210_000_000_000,
    secondOffer: 4_900_000_000_000,
    startupUpgradeTargets: [
        ["FocusWires", 2],
        ["Neural Accelerators", 2],
        ["Speech Processor Implants", 2],
        ["Nuoptimal Nootropic Injector Implants", 2],
        ["Smart Factories", 2],
        ["Smart Storage", 2],
        ["ABC SalesBots", 2],
        ["Project Insight", 2],
    ],
    round1UpgradeTargets: [
        ["Smart Factories", 12],
        ["Smart Storage", 10],
        ["ABC SalesBots", 8],
        ["Project Insight", 8],
    ],
    tobaccoUpgradeTargets: [
        ["Wilson Analytics", 14],
        ["FocusWires", 18],
        ["Neural Accelerators", 18],
        ["Speech Processor Implants", 18],
        ["Nuoptimal Nootropic Injector Implants", 18],
    ],
    tobaccoAdVerts: 83,
    tobaccoProductBaseSpend: 10_000_000_000,
};
