// /lib/daemon/services.js

export const SERVICE_TYPES = {
    PERSISTENT: "PERSISTENT",
    CONDITIONAL: "CONDITIONAL",
    ONE_SHOT: "ONE_SHOT",
    ARCHIVED: "ARCHIVED",
};

export const SERVICES = [
    {
        id: "uhm",
        name: "/controllers/uhm.js",
        host: "home",
        threads: 1,
        args: [],
        tail: true,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "main execution engine",
    },
    {
        id: "stock-trader",
        name: "/economy/stock-trader.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        policyFlag: "allowStockTrading",
        stopWhenBlocked: true,
        purpose: "market access buyer and daemon-controlled stock trader",
    },
    {
        id: "bootstrap-money",
        name: "/tools/bootstrap-money.js",
        host: "home",
        threads: 1,
        args: ["--target", "n00dles", "--stop-home-ram", 64, "--reserve", 8],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        maxHomeRam: 64,
        purpose: "tiny fresh-run money engine",
    },
    {
        id: "home-ram-buyer",
        name: "/economy/home-ram-buyer-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 10000, "--min-money", 1_000_000],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 16,
        purpose: "bootstrap-safe home RAM upgrades",
    },
    // ARCHIVED / FUTURE REFACTOR
    {
        id: "faction-ai",
        name: "/singularity/faction-ai.js",
        type: SERVICE_TYPES.ARCHIVED,
        enabled: false,
        reason: "Archive for future /lib/daemon/factions.js refactor",
    },
    {
        id: "faction-work",
        name: "/tools/faction-work-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--force", "false"],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 8,
        stopWhenBlocked: true,
        purpose: "daemon-controlled faction reputation work",
        policyFlag: "allowFactionWork",
    },
    {
        id: "int-travel",
        name: "/singularity/int-travel.js",
        type: SERVICE_TYPES.ARCHIVED,
        enabled: false,
        reason: "Future conditional Singularity stat-grind service",
    },

    {
        id: "reset-planner",
        name: "/singularity/reset-planner.js",
        type: SERVICE_TYPES.ARCHIVED,
        enabled: false,
        reason: "Future /lib/daemon/progression.js logic",
    },

    {
        id: "augmentation-planner",
        name: "/singularity/augmentation-planner.js",
        type: SERVICE_TYPES.ARCHIVED,
        enabled: false,
        reason: "Future conditional daemon service after lifecycle cleanup",
    },
    {
        id: "reset-executor",
        name: "/tools/reset-executor-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--execute", true],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 128,
        policyFlag: "allowReset",
        stopWhenBlocked: false,
        purpose: "reset planner dry-run and future augmentation installer",
    },
    {
        id: "daemon-hud",
        name: "/tools/daemon-hud.js",
        host: "home",
        threads: 1,
        args: [],
        tail: true,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "daemon-dashboard",
    },
    {
        id: "progression-buyer",
        name: "/economy/progression-buyer-service.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 512,
        purpose: "large progression purchases",
    },
    // RETIRED SERVICE - keep for reference, but do not register it with the daemon.
    // Fresh-start life owns BN1/BN4 study/shoplift bootstrapping now, and showing this
    // disabled legacy entry in Services only clutters the dashboard.
    // {
    //     id: "crime-bootstrap",
    //     name: "/tools/crime-bootstrap.js",
    //     host: "home",
    //     threads: 1,
    //     args: ["--crime", "Shoplift", "--stop-money", 10_000_000, "--stop-home-ram", 64],
    //     tail: false,
    //     type: SERVICE_TYPES.CONDITIONAL,
    //     keepAlive: true,
    //     enabled: false,
    //     requiresSingularity: false,
    //     maxHomeRam: 64,
    //     stopWhenBlocked: true,
    //     purpose: "legacy early cash bootstrap; replaced by fresh-start-life-service",
    // },
    {
        id: "fresh-start-life",
        name: "/tools/fresh-start-life-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 5000,
            "--study-until-hacking", 20,
            "--crime", "Shoplift",
            "--crime-min-chance", 0,
            "--stop-money", 10_000_000,
            "--stop-home-ram", 128,
            "--focus", false,
            "--bitnodes", "1,4",
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        completionFile: "/data/fresh-start-life-complete.txt",
        keepAlive: false,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 8,
        purpose: "BN1/BN4 fresh install bridge",
    },
    {
        id: "bn9-level-study",
        name: "/tools/bn9-level-study-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 5000,
            "--focus", false,
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 8,
        bitNodes: [9],
        purpose: "BN9 hacking-level blocker study controller",
    },
    {
        id: "gang-manager",
        name: "/tools/gang-manager-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 2500,
            "--reserve", 0,
            "--create", true,
            "--faction", "Slum Snakes",
            "--buy-equipment", true,
            "--ascend", true,
            "--asc-mult", 10,
            "--fast-asc-mult", 100,
            "--debug", true,
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 32,
        bitNodes: [2],
        purpose: "BN2 gang recruitment, tasking, equipment, and ascension manager",
    },
    {
        id: "darkweb-buyer",
        name: "/economy/darkweb-buyer-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--reserve", 200_000],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,

        // IMPORTANT
        completionFile: "/data/darkweb-buyer-complete.txt",
        keepAlive: false,
        enabled: true,
        requiresSingularity: false,
        minMoney: 200_000,
        purpose: "TOR and darkweb program purchases",
    },
    {
        id: "darknet-scout",
        name: "/tools/darknet-scout.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 60000,
            "--depth", 3,
            "--password", "",
            "--auth", true,
            "--peek", true,
            "--spread", true,
            "--realloc", false,
            "--stasis", false,
            "--once", false,
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        policyFlag: null,
        stopWhenBlocked: false,
        purpose: "DarkscapeNavigator darknet scouting and dnet state capture",
    },
    {
        id: "server-purchaser",
        name: "/economy/server-purchaser-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 10000, "--debug", true],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,

        // Early scaling gate
        minHomeRam: 32,
        minMoney: 1_000_000,

        // Do not block it during bootstrap anymore
        disabledPhases: [],

        policyFlag: "allowServerPurchases",
        stopWhenBlocked: true,
        purpose: "early purchased server scaling",
    },
    {
        id: "daemon-telemetry",
        name: "/tools/daemon-telemetry-service.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 128,
        purpose: "daemon-history-telemetry",
    },
    // RETIRED SERVICE - keep for reference, but do not register it with the daemon.
    // Session stats are written inside /lib/daemon/state.js now; running or listing
    // this service can make the dashboard look like something is blocked when it is not.
    // {
    //     id: "daemon-session",
    //     name: "/tools/daemon-session-service.js",
    //     host: "home",
    //     threads: 1,
    //     args: [],
    //     tail: false,
    //     type: SERVICE_TYPES.CONDITIONAL,
    //     keepAlive: true,
    //     enabled: false,
    //     requiresSingularity: false,
    //     minHomeRam: 128,
    //     stopWhenBlocked: true,
    //     purpose: "legacy daemon-session-tracking; session stats now update inside state.js",
    // },
    {
        id: "target-service",
        name: "/tools/target-service.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.PERSISTENT,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        purpose: "target-selection-state",
    },
    {
        id: "faction-observer",
        name: "/tools/faction-observer-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--singularity", true],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "safe faction progression observer",
    },
    {
        id: "augmentation-buyer",
        name: "/tools/augmentation-buyer-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 15000,
            "--max-price", 1_000_000_000_000,
            "--reserve", 1_000_000,
            "--use-policy-reserve", false,
            "--force-buy", false
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,

        // Do NOT policy-block this service.
        // It must always run so it can create /data/augmentation-plan.txt.
        policyFlag: null,
        stopWhenBlocked: false,

        purpose: "augmentation planner and policy-gated buyer",
    },
    {
        id: "augmentation-data-builder",
        name: "/tools/augmentation-data-builder.js",
        host: "home",
        threads: 1,
        args: ["--force", false],
        tail: false,
        type: SERVICE_TYPES.ONE_SHOT,
        keepAlive: false,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 128,
        completionFile: "/data/augmentation-data-builder-complete.txt",
        purpose: "build augmentation data cache once",
    },
    {
        id: "faction-donation",
        name: "/tools/faction-donation-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--force", "false"],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 128,
        purpose: "daemon-controlled faction rep donations",
        policyFlag: "allowFactionDonation",
        stopWhenBlocked: true,
    },
    {
        id: "faction-join",
        name: "/tools/faction-join-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--force", "false"],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 8,
        policyFlag: "allowFactionJoin",
        stopWhenBlocked: true,
        purpose: "daemon-controlled faction invitation joiner",
    },
    {
        id: "faction-progress-watch",
        name: "/tools/faction-progress-watch.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: false,
        requiresSingularity: false,
        minHomeRam: 128,
        purpose: "tracks faction rep progress and refreshes work/donation plans",
    },
    {
        id: "backdoor-service",
        name: "/tools/backdoor-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--execute", true, "--debug", true],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 8,

        policyFlag: "allowBackdoors",
        stopWhenBlocked: false,

        purpose: "daemon-controlled faction backdoor orchestration",
    },

    {
        id: "home-core-buyer",
        name: "/economy/home-core-buyer-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 10000,
            "--min-money", 1_000_000,
            "--reserve", 500_000,
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 32,
        minMoney: 1_000_000,

        // Let the service control its own reserve.
        // Do not block it with daemon home RAM policy yet.
        policyFlag: null,

        stopWhenBlocked: false,
        purpose: "bootstrap-safe home core upgrades",
    },
    {
        id: "hacknet-buyer",
        name: "/economy/hacknet-buyer-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 1000,
            "--nodes", 0,
            "--level", 0,
            "--ram", 0,
            "--cores", 0,
            "--cache", 0,
            "--reserve", 0,
            "--max-payback", 0,
            "--hash-buffer-minutes", 120,
            "--sell-value", 2_000_000,
            "--max-purchases", 1000,
            "--debug", true,
            "--toast", false,
            "--terminal", false,
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 16,
        minMoney: 0,
        policyFlag: "allowHacknet",
        stopWhenBlocked: false,
        purpose: "daemon-controlled Hacknet node scaling",
    },
    {
        id: "hacknet-hash-spender",
        name: "/economy/hacknet-hash-spender-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 5000,
            "--upgrade", "auto",
            "--reserve", 0,
            "--min", 4,
            "--max-spends", 500,
            "--debug", true,
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 16,
        policyFlag: "allowHacknet",
        requiresRunningService: "/economy/hacknet-buyer-service.js",
        bitNodes: [9],
        stopWhenBlocked: false,
        purpose: "BN9 Hacknet hash spending",
    },
    {
        id: "destroy-node",
        name: "/tools/destroy-node-service.js",
        host: "home",
        phases: ["destroy-node", "prep-world-daemon"],
        threads: 1,

        args: [
            "--next", "auto",
            "--script", "daemon.js",
            "--clean", true,
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: false,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 128,
        policyFlag: "allowReset",
        stopWhenBlocked: false,
        purpose: "final BitNode destruction executor",
    },
    {
        id: "dashboard-command-runner",
        name: "/tools/dashboard-command-runner.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.PERSISTENT,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "dashboard-debug-command-runner",
    },
    {
        id: "dashboard-state-writer",
        name: "/tools/dashboard-state-writer.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 3000],
        tail: false,
        type: SERVICE_TYPES.PERSISTENT,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "dashboard-ui-state-output",
    },
    {
        id: "network-topology-writer",
        name: "/tools/network-topology-writer.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 10000],
        tail: false,
        type: SERVICE_TYPES.PERSISTENT,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "dashboard-network-topology-output",
    },
    {
        id: "daemon-reasoning-writer",
        name: "/tools/daemon-reasoning-writer.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 5000],
        tail: false,
        type: SERVICE_TYPES.PERSISTENT,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "dashboard-daemon-reasoning-output",
    },
];

export function getEnabledServices() {
    return SERVICES.filter(s =>
        s.type !== SERVICE_TYPES.ARCHIVED &&
        (
            s.enabled === true ||
            s.stopWhenBlocked === true
        )
    );
}
