// /lib/daemon/services.js

export const SERVICE_TYPES = {
    PERSISTENT: "PERSISTENT",
    CONDITIONAL: "CONDITIONAL",
    ONE_SHOT: "ONE_SHOT",
    ARCHIVED: "ARCHIVED",
};

export const SERVICES = [
    {
        id: "uhm",
        name: "/controllers/uhm.js",
        host: "home",
        threads: 1,
        args: [],
        tail: true,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "main execution engine",
    },
    {
        id: "stock-trader",
        name: "/economy/stock-trader.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: false,
        requiresSingularity: false,
        requiresTixApi: true,
        policyFlag: "allowStockTrading",
    },
    {
        id: "bootstrap-money",
        name: "/tools/bootstrap-money.js",
        host: "home",
        threads: 1,
        args: ["--target", "n00dles", "--stop-home-ram", 64, "--reserve", 8],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        maxHomeRam: 64,
        purpose: "tiny fresh-run money engine",
    },
    {
        id: "home-ram-buyer",
        name: "/economy/home-ram-buyer-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 10000, "--min-money", 1_000_000, "--reserve", 1_000_000],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 16,
        purpose: "bootstrap-safe home RAM upgrades",
    },
    // ARCHIVED / FUTURE REFACTOR
    {
        id: "faction-ai",
        name: "/singularity/faction-ai.js",
        type: SERVICE_TYPES.ARCHIVED,
        enabled: false,
        reason: "Archive for future /lib/daemon/factions.js refactor",
    },
    {
        id: "faction-work",
        name: "/tools/faction-work-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--force", "false"],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: true,
        minHomeRam: 256,
        stopWhenBlocked: true,
        purpose: "daemon-controlled faction reputation work",
        policyFlag: "allowFactionWork",
    },
    {
        id: "int-travel",
        name: "/singularity/int-travel.js",
        type: SERVICE_TYPES.ARCHIVED,
        enabled: false,
        reason: "Future conditional Singularity stat-grind service",
    },

    {
        id: "reset-planner",
        name: "/singularity/reset-planner.js",
        type: SERVICE_TYPES.ARCHIVED,
        enabled: false,
        reason: "Future /lib/daemon/progression.js logic",
    },

    {
        id: "augmentation-planner",
        name: "/singularity/augmentation-planner.js",
        type: SERVICE_TYPES.ARCHIVED,
        enabled: false,
        reason: "Future conditional daemon service after lifecycle cleanup",
    },
    {
        id: "reset-executor",
        name: "/tools/reset-executor-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--execute", false],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: true,
        minHomeRam: 128,
        policyFlag: "allowReset",
        stopWhenBlocked: false,
        purpose: "reset planner dry-run and future augmentation installer",
    },
    {
        id: "daemon-hud",
        name: "/tools/daemon-hud.js",
        host: "home",
        threads: 1,
        args: [],
        tail: true,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "daemon-dashboard",
    },
    {
        id: "progression-buyer",
        name: "/economy/progression-buyer-service.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 512,
        purpose: "large progression purchases",
    },
    {
        id: "crime-bootstrap",
        name: "/tools/crime-bootstrap.js",
        host: "home",
        threads: 1,
        args: ["--crime", "mug", "--stop-money", 10_000_000, "--stop-home-ram", 64],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: true,
        maxHomeRam: 64,
        purpose: "early BN4 cash bootstrap",
    },
    {
        id: "darkweb-buyer",
        name: "/economy/darkweb-buyer-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--reserve", 200_000],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,

        // IMPORTANT
        completionFile: "/data/darkweb-buyer-complete.txt",
        keepAlive: false,
        enabled: true,
        requiresSingularity: false,
        minMoney: 200_000,
        purpose: "TOR and darkweb program purchases",
    },
    {
        id: "server-purchaser",
        name: "/economy/server-purchaser-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 10000, "--debug", true],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,

        // Early scaling gate
        minHomeRam: 32,
        minMoney: 1_000_000,

        // Do not block it during bootstrap anymore
        disabledPhases: [],

        purpose: "early purchased server scaling",
    },
    {
        id: "daemon-telemetry",
        name: "/tools/daemon-telemetry-service.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 128,
        purpose: "daemon-history-telemetry",
    },
    {
        id: "daemon-session",
        name: "/tools/daemon-session-service.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 128,
        purpose: "daemon-session-tracking",
    },
    {
        id: "target-service",
        name: "/tools/target-service.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.PERSISTENT,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        purpose: "target-selection-state",
    },
    {
        id: "faction-observer",
        name: "/tools/faction-observer-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--singularity", false],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 64,
        purpose: "safe faction progression observer",
    },
    {
        id: "augmentation-buyer",
        name: "/tools/augmentation-buyer-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 15000,
            "--max-price", 1_000_000_000_000,
            "--reserve", 100_000_000,
            "--use-policy-reserve", false,
            "--force-buy", false
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: true,
        minHomeRam: 128,

        // Do NOT policy-block this service.
        // It must always run so it can create /data/augmentation-plan.txt.
        policyFlag: null,
        stopWhenBlocked: false,

        purpose: "augmentation planner and policy-gated buyer",
    },
    {
        id: "augmentation-data-builder",
        name: "/tools/augmentation-data-builder.js",
        host: "home",
        threads: 1,
        args: ["--force", false],
        tail: false,
        type: SERVICE_TYPES.ONE_SHOT,
        keepAlive: false,
        enabled: true,
        requiresSingularity: true,
        minHomeRam: 128,
        purpose: "build augmentation data cache once",
    },
    {
        id: "faction-donation",
        name: "/tools/faction-donation-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--force", "false"],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: true,
        minHomeRam: 128,
        purpose: "daemon-controlled faction rep donations",
        policyFlag: "allowFactionDonation",
        stopWhenBlocked: true,
    },
    {
        id: "faction-join",
        name: "/tools/faction-join-service.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000, "--force", "false"],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: true,
        minHomeRam: 64,
        policyFlag: "allowFactionJoin",
        stopWhenBlocked: true,
        purpose: "daemon-controlled faction invitation joiner",
    },
    {
        id: "faction-progress-watch",
        name: "/tools/faction-progress-watch.js",
        host: "home",
        threads: 1,
        args: ["--refresh", 15000],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: false,
        requiresSingularity: true,
        minHomeRam: 128,
        purpose: "tracks faction rep progress and refreshes work/donation plans",
    },
    {
        id: "backdoor-service",
        name: "/tools/backdoor-service.js",
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: true,
        policyFlag: "allowBackdoors",
        args: [
            "--refresh",
            15000,
            "--execute",
            true,
        ],
        purpose: "daemon-controlled faction backdoor orchestration",
    },
    {
        id: "home-core-buyer",
        name: "/economy/home-core-buyer-service.js",
        host: "home",
        threads: 1,
        args: [
            "--refresh", 10000,
            "--min-money", 1_000_000,
            "--reserve", 500_000,
        ],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: true,
        enabled: true,
        requiresSingularity: false,
        minHomeRam: 32,
        minMoney: 1_000_000,

        // Let the service control its own reserve.
        // Do not block it with daemon home RAM policy yet.
        policyFlag: null,

        stopWhenBlocked: false,
        purpose: "bootstrap-safe home core upgrades",
    },
    {
        id: "destroy-node",
        name: "/tools/destroy-node.js",
        host: "home",
        threads: 1,
        args: [],
        tail: false,
        type: SERVICE_TYPES.CONDITIONAL,
        keepAlive: false,
        enabled: true,
        requiresSingularity: true,
        minHomeRam: 128,
        policyFlag: "allowReset",
        stopWhenBlocked: false,
        purpose: "final BitNode destruction executor",
    },
    {
        id: "dashboard-state-writer",
        script: "/tools/dashboard-state-writer.js",
        args: ["--refresh", 3000],
        enabled: true,
        keepAlive: true,
        purpose: "Writes /data/ui/dashboard-state.txt for F12 overlay."
    }
];

export function getEnabledServices() {
    return SERVICES.filter(s => s.enabled === true && s.type !== SERVICE_TYPES.ARCHIVED);
}